-- QUOTELY Catalogue Expansion
-- 273 original editorial thoughts; existing 28 records remain untouched.
-- Expected total after import: 301 quotes.
-- These entries are attributed to QUOTELY rather than third parties.


-- WISDOM (39 new)
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Clarity grows when certainty makes room for questions', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A useful question can outlive a clever answer', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Experience becomes wisdom only after reflection', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Good judgment grows from mistakes examined without excuses', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Attention is often the first form of understanding', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A precise doubt can be more useful than a vague certainty', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Knowing more matters less than noticing what matters', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Good thinking separates what is known from what is familiar', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Understanding includes knowing where understanding ends', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A calm mind can see distinctions urgency erases', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Facts become useful when placed in the right relationship', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Complexity deserves patience rather than admiration', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Better reasoning begins when conclusions remain revisable', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Precision is a form of respect for reality', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Patterns teach best when exceptions are allowed to speak', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Learning accelerates when embarrassment stops controlling questions', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Insight often hides in the detail everyone agreed to ignore', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Good advice survives contact with context', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Knowledge collects facts while judgment decides their weight', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Before defending an idea, decide what could change your mind', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('An explanation is strongest when it survives a simpler wording', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Thought improves when obvious is replaced with why', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A thoughtful pause can prevent a week of correction', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('The first explanation is not always the deepest one', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Strong mental models remain tools instead of identities', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Understanding a system requires watching it under stress', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Some lessons appear only after repetition stops looking accidental', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Reasoning improves when assumptions are made visible', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A conclusion should carry the weight of its evidence', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Listening well can reveal the question beneath the question', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Useful knowledge changes decisions rather than merely vocabulary', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('The mature question asks not only what works but what it changes', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Good judgment notices consequences beyond the immediate result', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Curiosity is strongest when it can challenge its own favorite answer', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Learning becomes durable when explanation meets application', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Uncertainty becomes manageable when it is named precisely', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('An answer gains value when its limits are understood', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Perspective changes when the frame of the problem changes', 'QUOTELY', 'wisdom', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Wisdom is often the discipline of choosing what deserves attention', 'QUOTELY', 'wisdom', datetime('now'));

-- LIFE (39 new)
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Ordinary days are where most of a life is built', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A life is shaped as much by repeated Tuesdays as remarkable days', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Keep room in your plans for the person you are becoming', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Not every meaningful season announces itself while it happens', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Small routines quietly decide what large intentions become', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A full calendar and a full life are different measurements', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Some chapters end by fading rather than closing', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Life becomes lighter when every interest is not forced into a purpose', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Change often arrives gradually before becoming obvious', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Make decisions your future ordinary days can live with', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('There is value in a day that simply went well', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Do not postpone all your living until everything is organized', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('People change in increments too small for mirrors to notice', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Your pace is part of the life you are building', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Some of the best memories begin as inconvenient plans', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Leave a little energy for wonder after the work is done', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A meaningful life can contain long unremarkable stretches', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('What you repeat eventually becomes part of what you call yourself', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Life asks for adjustment more often than reinvention', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Not every detour needs to justify itself with a lesson', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Attention is one of the clearest records of how life was spent', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Make room for interests that have no résumé value', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Some seasons are for building and others for understanding', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('The future is assembled from decisions that felt small at the time', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Being present is difficult because the present rarely announces its importance', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Life improves when enough is allowed to mean enough', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Do not let efficiency remove every pleasant inconvenience', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A good day does not need to prove a perfect life', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Keep traditions that still carry meaning rather than momentum', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Sometimes moving forward means making next week more livable', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('The life around a goal matters as much as reaching it', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Let changing your mind be part of changing your life', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Time makes ordinary moments expensive only after they are gone', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Growth can look like choosing differently in a familiar moment', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Some progress is visible only in what no longer controls you', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Leave space for plans that become better after they change', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A season can be valuable without becoming permanent', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Life rarely feels like a story while you are living the middle', 'QUOTELY', 'life', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('An ordinary moment can become important without warning', 'QUOTELY', 'life', datetime('now'));

-- INSPIRATIONAL (39 new)
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Begin before confidence has finished introducing itself', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Momentum often starts with a task too small to impress anyone', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('You do not need the whole map to improve your direction', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Make the next attempt easier to begin than the last', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Progress becomes believable after enough small promises are kept', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Start with what can be done before worrying about what can be admired', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A difficult beginning is still a beginning', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Your next useful step does not need to look ambitious', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Keep moving until uncertainty has new information to work with', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Improvement is often quieter than the frustration that preceded it', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Do the small part well enough that the larger part becomes possible', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Motivation is welcome but a workable routine is easier to depend on', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Let yesterday provide information rather than instructions', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Build evidence for yourself one completed step at a time', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('The distance ahead matters less when the direction is finally right', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('An imperfect attempt can teach what perfect planning cannot', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Give your future self something useful to continue', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Some breakthroughs are simply consistency becoming visible', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Do not wait to feel ready for work that creates readiness', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Turn the intimidating project into the next visible action', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Effort becomes easier to trust when it has somewhere specific to go', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Keep the goal large and the next step small', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A slow beginning can still create a strong direction', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Make progress measurable enough that discouragement cannot rewrite it', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Today only needs to move the work one honest step forward', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Capability grows where repetition is allowed to be awkward', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Do not underestimate what becomes normal after enough practice', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Your first version only needs to make the second possible', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Energy follows clarity more reliably than pressure', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Start where resistance is smallest and then keep going', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Every finished piece once existed as an unfinished inconvenience', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Give persistence a structure rather than only a slogan', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Make the work easier to return to', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A better system can carry you when enthusiasm cannot', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Small wins are how larger progress accumulates', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Continue long enough for early mistakes to become useful', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('The next attempt deserves what the last attempt taught you', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Ambition becomes practical when translated into today''s actions', 'QUOTELY', 'inspirational', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Move from wishing the work existed to leaving evidence it is being built', 'QUOTELY', 'inspirational', datetime('now'));

-- SUCCESS (39 new)
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Success becomes sustainable when the process survives ordinary days', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A result is stronger when you understand what made it repeatable', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Build systems that still work when excitement is absent', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Useful work compounds before recognition notices it', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Measure progress by what improves rather than what gets announced', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A strong outcome often begins with an unglamorous standard kept consistently', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Do not optimize the appearance of progress ahead of progress itself', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Reliable execution turns good intentions into something others can use', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Success without a maintainable process becomes an expensive accident', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Finish enough small things to learn how larger things get finished', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Quality is easier to scale when it is defined before it is demanded', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Choose metrics that reward the behavior you actually want', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Consistency matters because it makes improvement observable', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A deadline can create focus but a system creates continuity', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Build for the second use rather than only the first demonstration', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Progress accelerates when recurring problems receive permanent solutions', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Good work earns trust by behaving well after the presentation ends', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Make the standard clear enough that improvement has a direction', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('The strongest shortcut is removing work that never needed to exist', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Success is easier to repeat when its causes are documented', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Do not confuse being busy with reducing the distance to the goal', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Strong execution makes priorities visible in the calendar', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Build something useful before trying to make it impressive', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('An outcome becomes durable when maintenance has an owner', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Improve the bottleneck rather than the part easiest to polish', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Good strategy decides what deserves no time at all', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Results become meaningful when they can withstand inspection', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Make reliability part of the definition of done', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('The work that compounds is often work nobody celebrates immediately', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Success can be quiet: fewer errors, clearer decisions, better defaults', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Protect the practices that produced the result after the result arrives', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Scale what has been understood rather than merely noticed', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('An ambitious goal needs an ordinary operating rhythm', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Create feedback loops shorter than your excuses', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Completion is a skill strengthened by repeated use', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Make each project leave behind a better way of working', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Success includes knowing how the result was produced', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Good systems turn discipline from a daily argument into a default', 'QUOTELY', 'success', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Build a reputation from outcomes people can rely on', 'QUOTELY', 'success', datetime('now'));

-- COURAGE (39 new)
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Courage often sounds like a quiet yes when fear expected silence', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Being afraid and moving carefully forward can happen together', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Some brave decisions look ordinary from outside', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Courage is easier to recognize after the moment that required it', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Say the necessary thing without making cruelty part of the delivery', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Fear deserves information rather than automatic authority', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A boundary can be courageous when agreement would be easier', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Do not wait for discomfort to disappear before choosing what matters', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Bravery can mean staying with a difficult truth long enough to understand it', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Take the step that makes tomorrow''s fear more informed', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Courage can be measured by what you face without pretending it is easy', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Admitting uncertainty can require more strength than performing certainty', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Speak clearly when vagueness would protect you from responsibility', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Some risks become manageable only after they are named precisely', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Courage is not volume; sometimes it is refusing to be moved by noise', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Choose the difficult honesty that leaves less damage behind', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('You can respect fear without giving it the final vote', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Standing alone is easier when you know what you are standing for', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Ask for help before pride turns difficulty into isolation', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Changing direction can be brave when the old path has become familiar', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Do not confuse endurance with an obligation to remain', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Courage includes leaving situations that only reward your silence', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Take responsibility for the decision even when certainty is unavailable', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Bravery becomes practical when the frightening thing is broken into actions', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Some fears shrink only after they meet preparation', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Let your principles become visible when convenience tests them', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Apologizing sincerely can require more courage than defending yourself cleverly', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Do not make fear prove danger before examining the evidence', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Courage is often the willingness to be seen learning', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Make room for the possibility that the hard conversation goes well', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Choose the action you can respect even if the outcome is uncertain', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Being new at something is not a reason to hide from beginning', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Refusing a wrong shortcut can be a form of quiet bravery', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Courage grows when avoided things are approached in manageable pieces', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Tell the truth early enough that it can still help', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Sometimes the boldest move is to stop performing confidence', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Standards matter most when lowering them would be convenient', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Face the real problem before solving the comfortable substitute', 'QUOTELY', 'courage', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Bravery is giving uncertainty a deadline to stop controlling the decision', 'QUOTELY', 'courage', datetime('now'));

-- HAPPINESS (39 new)
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Happiness often enters through moments too small to schedule', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A pleasant ordinary day is not a lesser kind of success', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Notice what makes you smile before asking how to make it productive', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Joy becomes easier to find when it is not required to be impressive', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Some happiness comes from having nothing urgent to prove', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Keep a few pleasures that do not need optimization', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A good conversation can improve a day without solving anything', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Contentment is easier to hear when comparison becomes quieter', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Enjoying what is here is different from abandoning what could improve', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Small rituals can give ordinary time a shape worth returning to', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Happiness does not always arrive as excitement; sometimes it arrives as ease', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Let a good moment remain good without demanding that it last forever', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Gratitude becomes richer when it names something specific', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Make room for people with whom silence is comfortable', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Some of life''s best luxuries are unhurried', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Celebrate progress before immediately converting it into a new obligation', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Rest can be part of a good life rather than recovery from a bad schedule', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Keep noticing the things you once hoped would become normal', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Joy survives better when it is shared without being performed', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A lighter day can still be a meaningful day', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Do not make every hobby audition for usefulness', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Sometimes enough is the feeling that makes abundance visible', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Enjoy the meal before reviewing the restaurant', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Good memories often begin when nobody is trying to create one', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Protect a little time from measurement', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Comfort can be meaningful without becoming complacency', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Let laughter interrupt the plan', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Some happiness is simply the absence of unnecessary hurry', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Pay attention to what leaves you quietly glad afterward', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Familiar things can remain beautiful after novelty leaves', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Make space for anticipation because looking forward is part of enjoyment', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Not every free hour needs a better use', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Notice when a problem has ended instead of carrying its posture forward', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A peaceful routine can be an achievement worth protecting', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Happiness can coexist with unfinished work', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Allow good news to occupy the room before the next concern enters', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Some days deserve appreciation rather than analysis', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Keep people close who make ordinary time feel generous', 'QUOTELY', 'happiness', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A life can be ambitious without making joy wait for completion', 'QUOTELY', 'happiness', datetime('now'));

-- ART (39 new)
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Art begins where description stops being enough', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A creative choice becomes interesting when it could have been otherwise', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Make the work specific enough that someone can recognize a point of view', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Style grows from repeated decisions rather than decorative accidents', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Create beyond the first idea because familiarity often arrives before originality', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Good design removes confusion without removing character', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Art can make an ordinary detail impossible to overlook again', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Leave enough imperfection for the human hand to remain visible', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A blank page is not empty; it is undecided', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Creative work improves when taste becomes specific enough to guide revision', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Do not decorate what needs a clearer idea', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Restraint gives emphasis somewhere to land', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Make the piece say one thing clearly before asking it to say everything', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Revision is where intention learns to become visible', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Originality often begins by noticing what you cannot stop noticing', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Create with references then make decisions they did not make for you', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A strong composition tells the eye where to rest', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Art can preserve a feeling that explanation would flatten', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Let form participate in the meaning', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Good creative work rewards a second look without demanding the first', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Make choices that belong to this piece rather than merely the current trend', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('An unfinished work is a conversation still capable of changing direction', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Craft gives imagination a reliable way to arrive', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Sometimes the missing element is more space', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Creative confidence grows by surviving revision', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Do not mistake complexity for richness', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Art becomes personal when influences pass through real decisions', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('A detail earns attention when it strengthens the whole', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Make something you would still recognize without the signature', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Good typography can whisper hierarchy before a word is read', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Every medium has limits and style often begins by negotiating with them', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Create the version that teaches you what the idea actually is', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Aesthetic consistency is built from many small refusals', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Let the work breathe before deciding it needs more', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('An idea becomes art through choices rather than intention alone', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Composition is the discipline of deciding what deserves proximity', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Make room for surprise without surrendering control', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Creative work becomes clearer when unnecessary cleverness is removed', 'QUOTELY', 'art', datetime('now'));
INSERT INTO quotes (quote_text, author, category, created_at) VALUES ('Art does not need to be loud to leave an echo', 'QUOTELY', 'art', datetime('now'));


-- Optional verification
-- SELECT category, COUNT(*) FROM quotes WHERE is_active = 1 GROUP BY category ORDER BY category;
-- SELECT COUNT(*) AS total_active_quotes FROM quotes WHERE is_active = 1;